version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    build:
      context: .
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000" # Forward FastAPI port
    depends_on:
      - redis
    environment:
      PYTHONPATH: /workspace

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Forward Redis port